// Reproduce the pinned, bundled Leaflet assets. Runtime maps only request visible map tiles.
const fs = require('node:fs');
const path = require('node:path');

async function main() {
  const version = '1.9.4';
  const download = async (file) => {
    const response = await fetch(`https://unpkg.com/leaflet@${version}/${file}`, { signal: AbortSignal.timeout(20000) });
    if (!response.ok) throw new Error(`Leaflet asset HTTP ${response.status}`);
    return response.text();
  };
  const [js, css, license] = await Promise.all([download('dist/leaflet.js'), download('dist/leaflet.css'), download('LICENSE')]);
  const directory = path.resolve(__dirname, '../src/features/location/presentation/vendor');
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'leaflet_assets.ts'), `// Leaflet ${version}, BSD-2-Clause. See leaflet_license.txt. Generated by scripts/fetch_map_assets.js.\nexport const LEAFLET_JS = ${JSON.stringify(js)};\nexport const LEAFLET_CSS = ${JSON.stringify(css)};\n`);
  fs.writeFileSync(path.join(directory, 'leaflet_license.txt'), license);
  console.log(`Bundled Leaflet ${version}: ${js.length} JS characters, ${css.length} CSS characters.`);
}
main().catch((error) => { console.error(error.message); process.exitCode = 1; });
